### PR TITLE
[chore|helmchart-v0.1.2] vulnerability,helm-lint &backend condition fix.

### PR DESCRIPTION
**Pull request by adityagajbhiye9**
## Description
* helm lint workflow fix for dependency.
* update changelog and docs

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by adityagajbhiye9** [comment]
@FaGru3n  I have corrected the workflow. Please review and approve. 🤞

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by hzierer — APPROVED** [review]
LGTM

**Comment by FaGru3n** [comment]
@adityagajbhiye9  please make sure that the pr decriptions fits to your changes.

**Pull request merged**
